#!/bin/sh
DEPLOY_FOLDER=/home/utnso/elAlgoritmoDelRitmo

# Instalar las dependencias

echo Instalando cspec
cd cspec
make install
echo
echo
echo
echo Instalando commons
cd ../so-commons-library
make install
echo
echo
echo
echo Parser ansisop
cd ../ansisop-parser/parser
make install
echo
echo
echo
echo Dependencias instaladas
echo
echo
echo
echo Creando directorio del tp
mkdir $DEPLOY_FOLDER/elAlgoritmoDelRitmo
echo Directorio creado
echo
echo
echo
echo Copiando Consola
cd ../../
cp -rf CONSOLA $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Copiando Cpu
cp -rf CPU $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Copiando Nucleo
cp -rf NUCLEO $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Copiando Swap
cp -rf SWAP $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Copiando UMC
cp -rf UMC $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Copiando scripts ANSISOP
cp -rf scripts-ansisop $DEPLOY_FOLDER
echo Copiado exitoso
echo
echo
echo
echo Fin del deploy