#!/bin/sh
DEPLOY_FOLDER="/home/utnso/elAlgoritmoDelRitmo"

# Instalar las dependencias

echo Instalando Cspec
cd cspec
sudo make install
echo 
echo 
echo 
echo Instalando Commons
cd ../so-commons-library
sudo make install
echo 
echo 
echo 
echo Parser ansisop
cd ../ansisop-parser/parser
sudo make install
echo 
echo 
echo 
echo Instalando librerias globales
cd ../../"Sockets Maggie"
sudo make install
echo 
echo 
echo 
echo Dependencias instaladas
echo 
echo 
echo 
echo Creando directorio del tp
rm -rf $DEPLOY_FOLDER
mkdir $DEPLOY_FOLDER
echo Directorio creado
echo 
echo 
echo 
echo Copiando Consola
cd ../
cp -rf CONSOLA $DEPLOY_FOLDER
cd  /mnt/usb/UMC
gcc -o CONSOLA/src/consola -lcommons -ltheDebuggers
make install
echo Copiado y compilado exitoso
echo 
echo 
echo 
echo Copiando Cpu
cp -rf CPU $DEPLOY_FOLDER
cd  /mnt/usb/CPU
gcc -o CPU/src/CPU -lparser-ansisop -lcommons -ltheDebuggers
make install
echo Copiado exitoso
echo 
echo 
echo 
echo Copiando Nucleo
cp -rf NUCLEO $DEPLOY_FOLDER
cd  /mnt/usb/NUCLEO
gcc -o NUCLEO/src/nucleo -lpthread -lm -lcommons -lrt -lparser-ansisop
make install
echo Copiado exitoso
echo 
echo 
echo 
echo Copiando Swap
cp -rf SWAP $DEPLOY_FOLDER
cd  /mnt/usb/SWAP
gcc -o SWAP/src/swap -lcommons -ltheDebuggers
make install
echo Copiado exitoso
echo 
echo 
echo 
echo Copiando UMC
cp -rf UMC $DEPLOY_FOLDER
cd  /mnt/usb/UMC
gcc -o NUCLEO/src/umc -lcspecs -lcommons -lpthread -ltheDebuggers
make install
echo Copiado exitoso
echo 
echo 
echo 
echo Copiando scripts ANSISOP
cp -rf scripts-ansisop $DEPLOY_FOLDER
chmod +777 *
echo Copiado exitoso
echo 
echo 
echo 
echo Quitandole permisos root a los archivos
chown -R utnso:utnso $DEPLOY_FOLDER
echo Permisos fixeados
echo Fin del deploy