#!/usr/bin/env bash

#gcc NUCLEO/TESTS/testcpu.c -o testcpu
gcc CPU/src/cpu.c CPU/src/primitivas.c -o testcpu -lparser-ansisop -lcommons
gcc CONSOLA/src/consola.c -o testconsola
gcc NUCLEO/TESTS/testumc.c -o testumc
gcc NUCLEO/src/nucleo.c -o testnucleo -lpthread


echo "##fin compilacion"
#./testumc &
#pid[0]=$!
#sleep 2
./testnucleo &
pid[1]=$!
sleep 2
./testcpu 127.0.0.1 1202 127.0.0.1 1205 &
pid[2]=$!
sleep 1
./testconsola
pid[3]=$!
trap "kill ${pid[0]} ${pid[1]} ${pid[2]} ${pid[3]}; exit 1" EXIT
wait
