#!/usr/bin/env bash

#gcc NUCLEO/TESTS/testcpu.c -o testcpu
#gcc CPU/src/cpu.c CPU/src/primitivas.c -o testcpu -lparser-ansisop -lcommons
#gcc CONSOLA/src/consola.c -o testconsola
#gcc UMC/src/umc.c -o testumc
#gcc NUCLEO/TESTS/testumc.c -o testumc  -lpthread
gcc NUCLEO/TESTS/testconsola.c -o testconsola  -lpthread
gcc NUCLEO/src/nucleo.c COMUNES/nsockets.c -o testnucleo -lpthread
#gcc SWAP/src/swap.c -o testswap

echo "##fin compilacion"
#./testswap &
#pid[0]=$!
#sleep 2
#./testumc 127.0.0.1 1206 &
#pid[1]=$!
#sleep 2
./testnucleo &
pid[0]=$!
sleep 2
./testconsola &
pid[1]=$!
./testconsola&
pid[2]=$!
#sleep 2
#./testcpu 127.0.0.1 1202 127.0.0.1 1205 &
#pid[3]=$!
#sleep 1
#./testconsola
#pid[4]=$!
trap "kill ${pid[0]} ${pid[1]} ${pid[2]}; exit 1" EXIT
wait
