#!/usr/bin/env bash

#Compilaciones
gcc  NUCLEO/src/*.c COMUNES/nsockets.c -o NUCLEO/src/nucleo -lpthread -lm -lcommons -lrt -lparser-ansisop
cd SWAP/Debug/
make all
cd -
cd CPU/Debug/
make all
cd -
cd UMC/Debug/
make all
cd -


#gcc  SWAP/src/*.c -o SWAP/swap -lpthread -lm -lcommons -lrt -lparser-ansisop -ltheDebuggers
#gcc  CPU/src/*.c COMUNES/*.c -o CPU/cpu -lpthread -lm -lcommons -lrt -lparser-ansisop -ltheDebuggers
#gcc  UMC/src/*.c UMC/src/consola/*.c UMC/src/pedidos/*.c UMC/src/tabla_de_paginas/*.c UMC/src/hilos/*.c UMC/src/tlb/*.c UMC/src/pedidos/interfaces/*.c -o UMC/umc -lpthread -lm -lcommons -lrt -lparser-ansisop -ltheDebuggers


echo "##fin compilacion"
cd SWAP
./SWAP&
pid[0]=$!
cd -
sleep 2
cd UMC
./UMC&
pid[1]=$!
sleep 2
cd -
cd NUCLEO/src/
./nucleo &
pid[2]=$!
cd -
sleep 4
cd CPU
./CPU &
#pid[3]=$!
#cd -
#sleep 1
#./testconsola
#pid[4]=$!
trap "kill ${pid[0]} ${pid[1]} ${pid[2]} ${pid[3]}; exit 1" EXIT
wait

