#!/usr/bin/env bash
./testumc &
pid[0]=$!
sleep 1
./../src/nucleo &
pid[1]=$!
sleep 2
./testcpu &
pid[2]=$!
sleep 1
./testconsola
pid[3]=$!
trap "kill ${pid[0]} ${pid[1]} ${pid[2]} ${pid[3]}; exit 1" INT
wait

